### ISSUE TITLE
Anything Diffusion (v4.0) is a dead link

### ISSUE THREAD

**Issue by Fripe070** [Haidra-Org/AI-Horde-image-model-reference#121]
https://huggingface.co/andite/anything-v4.0 is linked as the homepage for `Anything DIffusion`, but that is now a 404 page as the user `andite` doesn't exist. The link should probably be changed to an activate page, or changed to [an archive](https://web.archive.org/web/20230301225949/https://huggingface.co/andite/anything-v4.0) in case a reputable one does not exist,

[Link](https://github.com/Haidra-Org/AI-Horde-image-model-reference/blob/71f021383988b25313246cc46c0d967cbd334d5f/stable_diffusion.json#L707C22-L707C65) to the line containing the dead link.

**Comment by tazlin** [comment]
Having a github action that checks for this and download link 404s would help us spot this automatically.

**Comment by tazlin** [comment]
Fixed via https://github.com/Haidra-Org/AI-Horde-image-model-reference/pull/128
